### ISSUE TITLE
About errors that occurred while downloading CC_textures

### ISSUE THREAD

**Issue by skyleryy** [sherwinbahmani/cc3d#7]
Hi,

Thank you for your great work.

I have failed to download the cc_textures. Some of the information is shown below：
“
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
No zip or downloads found for asset: TilesSubstance016
No downloadFolders or default or downloadFiletypeCategories found for asset: RockBrush001
Download asset: Asphalt030 of 0/1593
Bad zip file given as input. File is not a zip file
”
And the error trace back to "blenderproc/scripts/download_cc_textures.py", line 97, in cli SetupUtility.extract_from_response(current_folder, response)

If you may, could you please provide a compressed package of the CC_textures files. 

Thank you very very much!

**Comment by sherwinbahmani** [comment]
Hi,

I don't want to share the dataset files, since I don't own them and don't want to get into trouble distributing data from other resources.

Did you install the blenderproc through the rendering package or are you using it through pip? How about downloading these files through the original blenderproc package? Since downloading the texture files is down to the original blenderproc package, I don't think it is a problem from our side. So better ask in the blenderproc github, if it doesn't work in the original repo as well.

**Comment by skyleryy** [comment]
Thanks for the reply,
I installed the blenderproc through pip. And I also failed to downloading these files through the original blenderproc package.   I've already asked the blenderproc github. But unfortunately, so far they have not replied.

**Comment by sherwinbahmani** [comment]
If they don't reply, you could also just take any png texture file of the internet. These texture files are just used for the floor texture in blender, so the impact shouldn't be big. You could even just have it as one png file with the same color.

Or take floorplan texture from here: https://github.com/nv-tlabs/ATISS/tree/6b46c1133e8f67927330cbc662898a79fb2b86cb/demo/floor_plan_texture_images
Though we find these texture very difficult to learn in our setting, since they are more complicated. We mainly used very simple floorplan textures with just simple colors.

**Comment by skyleryy** [comment]
Thank you very much for your reply, 
you are so helpful， 
I will try to take some png texture file of the internet.
